#!/bin/bash

set -euo pipefail

if command -v gh >/dev/null && gh auth status &>/dev/null; then
    export GITHUB_TOKEN=$(gh auth token)
fi

if command -v zsh >/dev/null; then
    sudo chsh -s $(command -v zsh) $USER
fi

if command -v chezmoi >/dev/null; then
  chezmoi init --apply --source $PWD
  exit 0
fi

if command -v mise >/dev/null; then
  mise exec chezmoi -- chezmoi init --apply --source $PWD
  exit 0
fi

sh -c "$(curl -fsLS get.chezmoi.io)" -- init --apply --source $PWD
exit 0

